#!/bin/sh
# Move this file to /usr/local/sbin

vmware-hgfsclient | while read folder; do
    vmwpath="/mnt/hgfs/${folder}"
    if [ ! -d "$vmwpath" ]; then {
        echo "[i] Mounting ${folder}   (${vmwpath})"
        sudo mkdir -p "${vmwpath}"
        sudo umount -f "${vmwpath}" 2>/dev/null
        sudo vmhgfs-fuse -o allow_other -o auto_unmount ".host:/${folder}" "${vmwpath}"
    }
    fi
done
sleep 2s
